import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

import { register } from "swiper/element/bundle";
import "./globals.css";

const inter = Quicksand({ subsets: ["latin"] });
register();

export const metadata: Metadata = {
  title: "Next.JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
